plot: true
save_data: true
model: SVM
nclasses: 6
proba: true
group_predictions: true
flash_time: 200
oversample: false
quality_thresholds:
  - [-100, -50, 'yellow', 0.5]
  - [-50, 50, 'green', 1.0]
  - [50, 100, 'yellow', 0.5]
update_speed_ms: 1000
update_plot_speed_ms: 250