plot: true
save_data: true
model: SVM
nclasses: 5
proba: true
group_predictions: true
flash_time: 150
oversample: false
epoch_length_ms: 500
baseline_ms : 100
quality_thresholds:
  - [-100, -50, 'yellow', 0.5]
  - [-50, 50, 'green', 1.0]
  - [50, 100, 'yellow', 0.5]
update_speed_ms: 1000
update_plot_speed_ms: 100